<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="1" time="0.003">
  <testcase classname="__main__.qa_CPM_cf" name="test_001_t" time="0.0025">
    <failure type="exceptions.AssertionError">0.6209 != 0.6949586868286133 within 4 places
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/edwin/Documents/GNURadio/gr-chaos/python/qa_CPM_cf.py", line 59, in test_001_t
    self.assertFloatTuplesAlmostEqual(expected_data_chebyshev, result_data,4)
  File "/home/edwin/prefix/lib/python2.7/dist-packages/gnuradio/gr_unittest.py", line 90, in assertFloatTuplesAlmostEqual
    self.assertAlmostEqual (a[i], b[i], places, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 561, in assertAlmostEqual
    raise self.failureException(msg)
    </failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
